global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "valerix-monitor"

scrape_configs:
  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:3001"]
        labels:
          service: "order-service"
          environment: "development"

  - job_name: "inventory-service"
    static_configs:
      - targets: ["inventory-service:3002"]
        labels:
          service: "inventory-service"
          environment: "development"

  - job_name: "prometheus"
    static_configs:
      - targets: ["104.214.168.187:9090"]
